### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-experimental-web-app-platform#26]
### 📋 Detailed Description

 As a developer, I want a README.md file in the root of the project, so that I can reference and store information about how things work and what stuff is.

### ✔️ Tasks

- [ ] Create the README.md file
- [ ] h1 tag title that matches repo name
- [ ] Disclaimer (if needed)
- [ ] GitHub Project that is tracking the work
- [ ] Description of application, who it is for, and what it does
- [ ] Technical specs of project (Stack)
- [ ] Getting Started
- [ ] How to Contribute
- [ ] License 
- [ ] French translation of all information
