### ISSUE TITLE
[US] - Implement the release-please github action

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-experimental-web-app-platform#44]
### 📋 Detailed Description

As a Developer, I want a GitHub Action to control releases and documentation updates related to releases, so that I can automate this process and keep it standardized

### ✔️ Tasks
- [x] [TSK] - Create the ./github/workflows/release-please.yml action file
- [x] [TSK] - Find the appropriate github action that would automate this and solve this
- [x] [TSK] - Configure, implement, and test integration
