### ISSUE TITLE
[US] - Deploy Postgraphile as a separate container within the deployed application

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-experimental-web-app-platform#77]
### 📋 Detailed Description

As a Developer, I want a Postgraphile API container to start up during the 'docker compose' step, so that I have another endpoint to test and use for the data within the database.

### ✔️ Tasks
- [x] [TSK] - Create the 'graphql-postgraphile' directory in the root of the repo
- [x] [TSK] - Create the Dockerfile or .noDockerfile
- [x] [TSK] - Add the necessary information to the root 'docker-compose.yml' file
- [x] [TSK] - Create the 'graphql-postgraphile.env' file
- [x] [TSK] - Update the 'check-dev.sh' script to check and/or create the 'graphql-postgraphile.env' file
- [x] [TSK] - Update the README.md to have deployment/configuration information

<details><summary>Acronyms</summary>
<p>

N/A

</p>
</details>
