### ISSUE TITLE
[TSK] - Create a page that utilizes the Hasura API to test functionality

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/DSCO-experimental-web-app-platform#78]
### 📋 Detailed Description

As a Developer, I would like an example of what a query against the Hasura API looks like, so that I can reference this for future work and development.

```[tasklist]
### ✔️ Tasks
- [x] #80
- [x] [TSK] - Add a POST mutation to page against the Hasura API
- [ ] [TSK] - Add a UPDATE mutation to page against the Hasura API
- [x] [TSK] - Add a DELETE mutation to page against the Hasura API
```

<details><summary>Acronyms</summary>
<p>

</p>
</details>
